name: flux
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohappyeyeballs=2.4.4=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - arrow-cpp=14.0.2=h374c478_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=mkl
  - bleach=6.1.0=pyhd8ed1ab_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - certifi=2024.12.14=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - cryptography=41.0.3=py311hdda0065_0
  - cuda=12.1.0=0
  - cuda-cccl=12.6.77=0
  - cuda-cccl_linux-64=12.6.77=0
  - cuda-command-line-tools=12.1.1=0
  - cuda-compiler=12.6.2=0
  - cuda-crt-dev_linux-64=12.6.20=0
  - cuda-crt-tools=12.6.20=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-dev_linux-64=12.6.77=0
  - cuda-cudart-static=12.6.77=0
  - cuda-cudart-static_linux-64=12.6.77=0
  - cuda-cudart_linux-64=12.6.77=0
  - cuda-cuobjdump=12.6.77=0
  - cuda-cupti=12.1.105=0
  - cuda-cuxxfilt=12.6.77=0
  - cuda-demo-suite=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.6.77=0
  - cuda-driver-dev_linux-64=12.6.77=0
  - cuda-gdb=12.6.77=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.6.2=0
  - cuda-libraries-static=12.6.2=0
  - cuda-nsight=12.6.77=0
  - cuda-nvcc=12.6.20=0
  - cuda-nvcc-dev_linux-64=12.6.20=0
  - cuda-nvcc-impl=12.6.20=0
  - cuda-nvcc-tools=12.6.20=0
  - cuda-nvcc_linux-64=12.6.20=0
  - cuda-nvdisasm=12.6.77=0
  - cuda-nvml-dev=12.6.77=2
  - cuda-nvprof=12.6.80=0
  - cuda-nvprune=12.6.77=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvrtc-static=12.6.85=0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvm-dev_linux-64=12.6.20=0
  - cuda-nvvm-impl=12.6.20=0
  - cuda-nvvm-tools=12.6.20=0
  - cuda-nvvp=12.6.80=0
  - cuda-opencl=12.3.52=0
  - cuda-opencl-dev=12.3.52=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.6.77=0
  - cuda-toolkit=12.1.0=0
  - cuda-tools=12.1.1=0
  - cuda-version=12.6=3
  - cuda-visual-tools=12.6.2=0
  - datasets=2.12.0=py311h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.6=py311h06a4308_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.4=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2023.10.0=py311h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gds-tools=1.8.0.34=0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - h5py=3.9.0=py311hdd6beaf_0
  - hdf5=1.12.1=h2b7332f_3
  - huggingface_hub=0.24.6=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.1=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py311h38be061_0
  - jupyter_server=1.24.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcublas-static=12.6.4.1=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcufft-static=11.3.0.4=0
  - libcufile=1.8.0.34=0
  - libcufile-dev=1.8.0.34=0
  - libcufile-static=1.11.1.6=0
  - libcurand=10.3.4.52=0
  - libcurand-dev=10.3.4.52=0
  - libcurand-static=10.3.7.77=0
  - libcurl=8.5.0=h251f7ec_0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusolver-static=11.7.1.2=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libcusparse-static=12.5.4.2=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnpp-static=12.3.1.54=0
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvfatbin-static=12.6.77=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjitlink-static=12.6.85=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libnvjpeg-static=12.3.3.54=0
  - libnvvm-samples=12.1.105=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hf1b16e4_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.14=py311h06a4308_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.16.1=pyhd8ed1ab_0
  - nbconvert-core=7.16.1=pyhd8ed1ab_0
  - nbconvert-pandoc=7.16.1=pyhd8ed1ab_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - notebook=6.5.6=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nsight-compute=2024.3.2.3=0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py311ha02d727_0
  - pandoc=3.1.12.1=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3=py311h06a4308_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.0.0=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - prompt_toolkit=3.0.41=hd8ed1ab_0
  - propcache=0.2.0=py311h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=14.0.2=py311hb6e97c4_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - python_abi=3.11=2_cp311
  - pytorch=2.1.0=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=23.2.0=py311h6a678d5_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.33.0=pyhd8ed1ab_0
  - regex=2023.10.3=py311h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py311h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.18.0=pyh0d859eb_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.1.0=py311
  - torchvision=0.16.0=py311_cu121
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.18=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.41.2=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.27.2
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - albumentations==1.3.1
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - argparse==1.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - beartype==0.16.4
      - blessed==1.20.0
      - braceexpand==0.1.7
      - cachetools==5.3.2
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - diffusers==0.26.3
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - fonttools==4.44.0
      - ftfy==6.1.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - gpustat==1.1.1
      - grpcio==1.59.2
      - huggingface-hub==0.27.0
      - hydra-core==1.3.2
      - imageio==2.32.0
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.9.0
      - lmdb==1.5.1
      - lpips==0.1.4
      - markdown==3.5.1
      - matplotlib==3.8.1
      - nvidia-ml-py==12.535.133
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.23.0
      - opencv-python-headless==4.8.1.78
      - piq==0.8.0
      - protobuf==4.23.4
      - psutil==5.9.6
      - pudb==2023.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.1.1
      - qudida==0.0.4
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - sentencepiece==0.1.99
      - sentry-sdk==1.34.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - timm==0.9.10
      - tokenizers==0.15.2
      - torch-fidelity==0.3.0
      - torchdiffeq==0.2.3
      - torchmetrics==1.2.0
      - transformers==4.39.3
      - urwid==2.2.3
      - urwid-readline==0.13
      - wandb==0.16.0
      - wcwidth==0.2.9
      - webdataset==0.2.75
      - werkzeug==3.0.1
      - xformers==0.0.22.post7
      - yarl==1.9.2
